export const COLORS = {
  primary: '#C0392B',
  primaryLight: '#E74C3C',
  primaryDark: '#922B21',
  background: '#F5F6FA',
  white: '#FFFFFF',
  gray100: '#F0F0F0',
  gray200: '#E0E0E0',
  gray400: '#AAAAAA',
  gray600: '#666666',
  gray800: '#333333',
  success: '#27AE60',
  warning: '#F39C12',
  danger: '#C0392B',
};

export const patients = [
  {
    id: '1',
    name: 'HASTA1',
    age: 62,
    diagnosis: 'Multipl Miyelom Evre II',
    lastVisit: '12.04.2024',
    nextVisit: '19.04.2024',
    status: 'Aktif Tedavi',
    avatar: null,
    phone: '+90 532 111 22 33',
    treatmentCycle: 3,
    totalCycles: 6,
  },
  {
    id: '2',
    name: 'HASTA2',
    age: 58,
    diagnosis: 'Multipl Miyelom Evre I',
    lastVisit: '10.04.2024',
    nextVisit: '24.04.2024',
    status: 'Takip',
    avatar: null,
    phone: '+90 533 222 33 44',
    treatmentCycle: 6,
    totalCycles: 6,
  },
  {
    id: '3',
    name: 'HASTA3',
    age: 71,
    diagnosis: 'Multipl Miyelom Evre III',
    lastVisit: '08.04.2024',
    nextVisit: '15.04.2024',
    status: 'Aktif Tedavi',
    avatar: null,
    phone: '+90 534 333 44 55',
    treatmentCycle: 1,
    totalCycles: 8,
  },
  {
    id: '4',
    name: 'HASTA4',
    age: 65,
    diagnosis: 'Multipl Miyelom Evre II',
    lastVisit: '05.04.2024',
    nextVisit: '22.04.2024',
    status: 'Remisyon',
    avatar: null,
    phone: '+90 535 444 55 66',
    treatmentCycle: 8,
    totalCycles: 8,
  },
];

export const appointments = [
  { id: '1', patientName: 'HASTA1', date: '19.04.2024', time: '09:00', type: 'Kontrol' },
  { id: '2', patientName: 'HASTA3', date: '15.04.2024', time: '10:30', type: 'Kemoterapi' },
  { id: '3', patientName: 'HASTA2', date: '24.04.2024', time: '14:00', type: 'Kontrol' },
  { id: '4', patientName: 'HASTA4', date: '22.04.2024', time: '11:00', type: 'Takip' },
];

export const educationModules = [
  {
    id: '1',
    title: 'Multipl Miyelom Nedir?',
    subtitle: 'Temel Bilgiler',
    duration: '10 dk',
    completed: true,
    icon: '🩸',
    content: 'Multipl miyelom, kemik iliğindeki plazma hücrelerinin kontrolsüz çoğalmasıyla ortaya çıkan bir kan kanseri türüdür.',
  },
  {
    id: '2',
    title: 'Tedavi Seçenekleri',
    subtitle: 'Kemoterapi & İmmünoterapi',
    duration: '15 dk',
    completed: true,
    icon: '💊',
    content: 'Multipl miyelom tedavisinde kemoterapi, steroidler, immünomodülatörler ve otolog kök hücre nakli kullanılmaktadır.',
  },
  {
    id: '3',
    title: 'Yan Etki Yönetimi',
    subtitle: 'Günlük Yaşam İpuçları',
    duration: '12 dk',
    completed: false,
    icon: '🛡️',
    content: 'Tedavi sürecindeki yan etkileri yönetmek için beslenme, egzersiz ve ilaç uyumuna dikkat edin.',
  },
  {
    id: '4',
    title: 'Beslenme Rehberi',
    subtitle: 'Sağlıklı Yaşam',
    duration: '8 dk',
    completed: false,
    icon: '🥗',
    content: 'Tedavi sürecinde bağışıklık sistemini destekleyen, protein açısından zengin bir beslenme programı önerilir.',
  },
];

export const surveyQuestions = [
  { id: '1', text: 'Bu hafta ağrı düzeyiniz nasıldı?', type: 'scale', min: 0, max: 10 },
  { id: '2', text: 'Yorgunluk hissettiniz mi?', type: 'yesno' },
  { id: '3', text: 'İştahınızda değişiklik var mı?', type: 'yesno' },
  { id: '4', text: 'Uyku kalitenizi nasıl değerlendirirsiniz?', type: 'scale', min: 1, max: 5 },
  { id: '5', text: 'Tedavinizle ilgili endişeleriniz var mı?', type: 'text' },
];
